module.exports = {

  EVENT_SERVICE_START: 'EVENT_SERVICE_START',

  EVENT_SERVICE_STOP: 'EVENT_SERVICE_STOP',

  FSWATCER_FILE_ADDED: 'FSWATCER_FILE_ADDED',

  QUEUE_FILE_ADDED: 'QUEUE_FILE_ADDED',

  S3CLIENT_FILE_SAVED: 'S3CLIENT_FILE_SAVED',

  S3CLIENT_FILE_FAIL: 'S3CLIENT_FILE_FAIL'
};
