module.exports = {

  SERVICE_START: 'SERVICE_START',

  SERVICE_STOP: 'SERVICE_STOP',

  EMERGED_FILE: 'EMERGED_FILE',

  PROCESS_FILE: 'PROCESS_FILE',

  MOVE_SUCCEED: 'MOVE_SUCCEED',

  MOVE_FAILING: 'MOVE_FAILING'
};
